### ISSUE TITLE
Bug: Plugin missing module.js

### ISSUE THREAD

**Issue by arvindpdmn** [grafana/plugin-tools#252] opened 2023-05-19 04:00 UTC
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

```shell
Grafana: 9.5.1
create-plugin: 1.3.3
```

### What happened?

Used `create-plugin` and ran the following commands on Windows 10 machine without any issue:
```
npx @grafana/create-plugin@latest
cd hw-example0-panel
yarn install
yarn dev
```

I modified `grafana-9.5.1\conf\defaults.ini` to allow unsigned plugin:
```
allow_loading_unsigned_plugins = hw-example0-panel
```

Then I started Grafana on command line: `.\grafana-server.exe`. Plugin is not loaded due to this error:
```
←[33mWARN ←[0m[05-19|06:24:52] Permitting unsigned plugin. This is not recommended ←[33mlogger←[0m=plugin.signature.validator ←[33mpluginID←[0m=hw-example0-panel
←[33mWARN ←[0m[05-19|06:24:52] Plugin missing module.js                 ←[33mlogger←[0m=plugin.loader ←[33mpluginID←[0m=hw-example0-panel ←[33mwarning←[0m="Missing module.js, If you loaded this plugin from git, make sure to compile it."
←
```

### What you expected to happen

There's module.ts file. I expect this to be correctly compiled to module.js. This error should not come.

### How to reproduce it (as minimally and precisely as possible)

See above.

### Environment

```shell
See above
```

### Additional context

Workaround: Use the old tool @grafana/toolkit from https://www.npmjs.com/package/@grafana/toolkit
This works correctly without any error and I can see the new plugin in the Grafana UI.

**Comment by jackw** [comment] 2023-05-23 08:31
>Used create-plugin and ran the following commands on Windows 10 machine

Closing as this looks like a duplicate of #237.

**Closed by jackw** 2023-05-23 08:31 UTC
