### ISSUE TITLE
Doc: add-support-for-variables.md is out of date

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/plugin-tools#454] opened 2023-10-09 18:51 UTC
The add support for variables page suggests to use `setVariableQueryEditor` which is deprecated.

**Comment by andresmgot** [comment] 2023-10-10 12:08
This is a duplicate of https://github.com/grafana/grafana/issues/63619 (I suggest to upvode that one). Let us know if you think otherwise!

**Closed by andresmgot** 2023-10-10 12:08 UTC
Labels: type/docs

**Comment by zoltanbedi** [comment] 2023-10-10 12:12
Thanks @andresmgot!
