### ISSUE TITLE
Bug: wrong path settings in .config/webpack/webpack.config.ts

### ISSUE THREAD

**Issue by 100kimch** [grafana/plugin-tools#272] opened 2023-06-04 08:50 UTC
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

```shell
{
  "module": "esnext"
  "scripts": {
    ...
    "dev:plugin": "webpack -c ./webpack.config.ts --env development"
  },
  "devDependencies": {
    ...
    "@grafana/data": "^9.5.2",
    "@grafana/e2e": "^9.5.2",
    "@grafana/e2e-selectors": "^9.5.2",
    "@grafana/eslint-config": "^5.1.0",
    "@grafana/runtime": "^9.5.2",
    "@grafana/tsconfig": "^1.2.0-rc1",
    "@grafana/ui": "^9.5.2",
    "typescript": "^4.9.4",
    "webpack": "^5.84.1",
    "webpack-cli": "^5.1.1",
  },
  "packageManager": "yarn@1.22.19"
}
```

### What happened?

Hi, there's a bug when compiling my react-based app using webpack.

I put the scaffolded setting files including webpack.config.ts to `./.config/*` and I created my own `webpack.config.ts`, `tsconfig.json` and other custom settings to root.

Here's the error logs when I execute `yarn dev:plugin`:

```bash
❯ yarn dev:plugin
yarn run v1.22.19
$ webpack -w --env development
[Webpack] development:  true { WEBPACK_WATCH: true, development: true }
[webpack-cli] Error: Cannot find the "/.../src/tsconfig.json" file.
Please check webpack and ForkTsCheckerWebpackPlugin configuration.
Possible errors:
  - wrong `context` directory in webpack configuration (if `configFile` is not set or is a relative path in the fork plugin configuration)
  - wrong `typescript.configFile` path in the plugin configuration (should be a relative or absolute path)
    at Object.assertTypeScriptSupport (/.../node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/TypeScriptSupport.js:40:15)
    at ForkTsCheckerWebpackPlugin.apply (/.../node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js:52:33)
    at createCompiler (/.../node_modules/webpack/lib/webpack.js:73:12)
    at create (/.../node_modules/webpack/lib/webpack.js:134:16)
    at webpack (/.../node_modules/webpack/lib/webpack.js:142:47)
    at WebpackCLI.f [as webpack] (/.../node_modules/webpack/lib/index.js:72:16)
    at WebpackCLI.createCompiler (/.../node_modules/webpack-cli/lib/webpack-cli.js:1718:29)
    at async WebpackCLI.runWebpack (/.../node_modules/webpack-cli/lib/webpack-cli.js:1810:20)
    at async Command.<anonymous> (/.../node_modules/webpack-cli/lib/webpack-cli.js:892:21)
    at async Command.parseAsync (/.../node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The `./.config/webpack/webpack.config.ts` seems to be wrong; It checks custom `tsconfig.json` file inside `/src/` directory not in the root folder.

### What you expected to happen

successfully compile the source files.

### How to reproduce it (as minimally and precisely as possible)

```bash
yarn dev:plugin
# webpack -w --env development
```

### Environment

```shell
-
```

**Comment by jackw** [comment] 2023-06-06 15:29
@100kimch Many thanks for reporting this issue you've come across with create-plugin.

>I put the scaffolded setting files including webpack.config.ts to ./.config/* and I created my own webpack.config.ts, tsconfig.json and other custom settings to root.

Are you trying to use create-plugin in a mono repo or custom directory structure of some sort? Maybe you could provide a reproduction repo to help us understand what's happening more easily?

**Comment by 100kimch** [comment] 2023-06-08 03:59
There is a public repo trying to implement grafana plugin on [@team-grass-farm/uncloudy-grapher](https://github.com/team-grass-farm/uncloudy-grapher/tree/feature/grafana-plugin)

**Comment by mckn** [comment] 2023-06-28 19:36
@100kimch is this still an issue? I cloned the repo and it seems to be building kind of OK for me.

**Comment by 100kimch** [comment] 2023-07-04 06:06
@mckn I couldn't see this issue recently. Thanks fot the fix and I'll check this soon

**Comment by mckn** [comment] 2023-07-04 06:38
Super, I'm closing this for now but happy to re-open if needed.

**Closed by mckn** 2023-07-04 06:38 UTC
